"""init

Revision ID: 3c7350c2a2da
Revises: 
Create Date: 2024-05-05 20:05:01.187862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7350c2a2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('env', sa.Enum('stage', 'preprod', 'prod', name='environmentenum'), nullable=False),
    sa.Column('domain', sa.Enum('canary', 'regular', name='domainenum'), nullable=False),
    sa.Column('locktime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_user_pkey')),
    sa.UniqueConstraint('id', name=op.f('auth_user_id_key')),
    sa.UniqueConstraint('login', name=op.f('auth_user_login_key'))
    )
    op.create_table('auth_refresh_token',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('auth_refresh_token_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('auth_refresh_token_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_refresh_token')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
